### ISSUE TITLE
Clowdflare bypass always failing

### ISSUE THREAD

**Issue by bevtrin** [calibrain/calibre-web-automated-book-downloader#120]
Hi,

I unfortunately can't get this working. the Cloudflare bypass continuously fails. I have it running behind gluetun. 

Log:
```
2025-04-06 08:51:50,802 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:101 - Starting Cloudflare bypass... Retry: 1 / 3
2025-04-06 08:51:50,803 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:106 - Attempt 1: Verification page detected. Trying to bypass...
2025-04-06 08:52:03,603 - cloudflare_bypasser - DEBUG - cloudflare_bypasser.py:66 - Verification button found. Attempting to click.
2025-04-06 08:52:10,469 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:101 - Starting Cloudflare bypass... Retry: 2 / 3
2025-04-06 08:52:10,469 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:106 - Attempt 2: Verification page detected. Trying to bypass...
2025-04-06 08:52:10,529 - werkzeug - INFO - _internal.py:97 - 127.0.0.1 - - [06/Apr/2025 08:52:10] "GET /request/api/status HTTP/1.1" 200 -
2025-04-06 08:52:15,644 - cloudflare_bypasser - DEBUG - cloudflare_bypasser.py:66 - Verification button found. Attempting to click.
2025-04-06 08:52:22,221 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:101 - Starting Cloudflare bypass... Retry: 3 / 3
2025-04-06 08:52:22,221 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:106 - Attempt 3: Verification page detected. Trying to bypass...
2025-04-06 08:52:26,757 - werkzeug - INFO - _internal.py:97 - 172.23.0.1 - - [06/Apr/2025 08:52:26] "GET /request/api/status HTTP/1.1" 200 -
2025-04-06 08:52:34,941 - cloudflare_bypasser - DEBUG - cloudflare_bypasser.py:66 - Verification button found. Attempting to click.
2025-04-06 08:52:40,695 - werkzeug - INFO - _internal.py:97 - 127.0.0.1 - - [06/Apr/2025 08:52:40] "GET /request/api/status HTTP/1.1" 200 -
2025-04-06 08:52:41,301 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:101 - Starting Cloudflare bypass... Retry: 4 / 3
2025-04-06 08:52:41,302 - cloudflare_bypasser - WARNING - cloudflare_bypasser.py:103 - Exceeded maximum retries. Bypass failed.
2025-04-06 08:52:41,342 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:118 - Bypass failed.
```

compose file:
```
services:
  gluetun-media:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun-media
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /srv/datadisk/data/appdata/gluetun-media:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESS}
      - PUID=1001
      - PGID=100
      - PORT_FORWARDING=off
      - BLOCK_MALICIOUS=off 
      - BLOCK_SURVEILLANCE=off 
      - BLOCK_ADS=off
    ports:
      - 8001:8000
      - 8084:8084 #calibre-web-automated-downloader webUI
    labels:
      - 'wud.watch=true'
      - 'wud.tag.include=^v\d{1,2}\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/qdm12/gluetun/releases/tag/v$${major}.$${minor}.$${patch}'
      - 'wud.trigger.include=dockercompose.mediaautomationgluetun'

  calibre-web-automated-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: calibre-web-automated-downloader
    network_mode: service:gluetun-media
    restart: unless-stopped
    depends_on:
      gluetun-media:
        condition: service_healthy
    volumes:
      - /srv/datadisk/data/media/temp:/cwa-book-ingest
    environment:
      - FLASK_PORT=8084
      - FLASK_DEBUG=false
      - BOOK_LANGUAGE=en
      - UID=1001
      - GID=100
      - LOG_LEVEL=debug
    labels:
      - 'wud.watch=true'
      - 'wud.tag.include=latest'
      - 'wud.link.template=https://github.com/calibrain/calibre-web-automated-book-downloader/releases'
      - 'wud.trigger.include=dockercompose.mediaautomationgluetun'
```

**Comment by calibrain** [comment]
Who is your VPN provider and can you try without VPN ?

**Comment by bevtrin** [comment]
I use surfshark. Will try without to see if that's the issue

**Comment by calibrain** [comment]
Hey, could you retry again ?
I just pushed a change that should better mimic a human user, so it might pass the cloudflare checks !

If not, I also added full tor support, (so you would not need an actual VPN)
You can see the compose here : https://github.com/calibrain/calibre-web-automated-book-downloader/blob/main/docker-compose.tor.yml

**Comment by barukh27** [comment]
I'm told that I must be root while creating the iptables. Any hints?

**Comment by calibrain** [comment]
Oh, sorry, I didn't properly add the permissions to the prod tor node ( I was playing with the dev one and forgot to push the prod cap_add)
Could you retry using the updated compose ? https://github.com/calibrain/calibre-web-automated-book-downloader/blob/main/docker-compose.tor.yml

**Comment by barukh27** [comment]
It doesn't work.

2025-04-15 21:56:42,196 - config - INFO - config.py:13 - USING_TOR: False

2025-04-15 21:56:42,201 - config - INFO - config.py:20 - BASE_DIR: /app

2025-04-15 21:56:42,205 - config - INFO - config.py:29 - STAT TMP_DIR: os.stat_result(st_mode=16877, st_ino=27407, st_dev=2050, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1744614026, st_mtime=1744706101, st_ctime=1744706101)

2025-04-15 21:56:42,207 - config - INFO - config.py:30 - STAT INGEST_DIR: os.stat_result(st_mode=16895, st_ino=27024, st_dev=2050, st_nlink=1, st_uid=0, st_gid=100, st_size=4096, st_atime=1744355496, st_mtime=1744706109, st_ctime=1744746761)

2025-04-15 21:56:42,208 - config - INFO - config.py:31 - CROSS_FILE_SYSTEM: False

2025-04-15 21:56:42,209 - config - INFO - config.py:51 - CUSTOM_DNS: []

2025-04-15 21:56:42,211 - config - INFO - config.py:57 - DOH_SERVER: 

2025-04-15 21:56:42,212 - config - INFO - config.py:65 - PROXIES: {}

2025-04-15 21:56:42,213 - config - INFO - config.py:75 - SUPPORTED_FORMATS: ['epub', 'mobi', 'azw3', 'fb2', 'djvu', 'cbz', 'cbr']

2025-04-15 21:56:44,639 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']

2025-04-15 21:56:48,964 - network - INFO - network.py:337 - AA_BASE_URL: https://annas-archive.org

2025-04-15 21:56:55,398 - backend - INFO - backend.py:162 - Starting download loop

**Comment by calibrain** [comment]
oh, `2025-04-15 21:56:42,196 - config - INFO - config.py:13 - USING_TOR: False`

Could you share your docker-compose ? It might be missing something

Please make sure to use the `    image: ghcr.io/calibrain/calibre-web-automated-book-downloader-tor:latest`

**Comment by barukh27** [comment]
Tkank you for your answer.

It get this in the logs:

```
[2025-04-16 11:26:20 +0200] [560] [INFO] Worker exiting (pid: 560)

[2025-04-16 11:26:20 +0200] [76] [ERROR] Worker (pid:560) was sent SIGKILL! Perhaps out of memory?

[2025-04-16 11:26:20 +0200] [790] [INFO] Booting worker with pid: 790

2025-04-16 11:26:23,425 - config - INFO - config.py:13 - os: <module 'os' from '/usr/local/lib/python3.10/os.py'>

2025-04-16 11:26:23,433 - config - INFO - config.py:13 - Path: <class 'pathlib.Path'>

2025-04-16 11:26:23,435 - config - INFO - config.py:13 - string_to_bool: <function string_to_bool at 0x7fa1fd9c60>

2025-04-16 11:26:23,436 - config - INFO - config.py:13 - LOG_ROOT: /var/log

2025-04-16 11:26:23,438 - config - INFO - config.py:13 - LOG_DIR: /var/log/cwa-book-downloader

2025-04-16 11:26:23,439 - config - INFO - config.py:13 - TMP_DIR: /tmp/cwa-book-downloader

2025-04-16 11:26:23,440 - config - INFO - config.py:13 - INGEST_DIR: /cwa-book-ingest

2025-04-16 11:26:23,441 - config - INFO - config.py:13 - STATUS_TIMEOUT: 3600

2025-04-16 11:26:23,441 - config - INFO - config.py:13 - USE_BOOK_TITLE: True

2025-04-16 11:26:23,443 - config - INFO - config.py:13 - MAX_RETRY: 10

2025-04-16 11:26:23,444 - config - INFO - config.py:13 - DEFAULT_SLEEP: 5

2025-04-16 11:26:23,446 - config - INFO - config.py:13 - USE_CF_BYPASS: True

2025-04-16 11:26:23,449 - config - INFO - config.py:13 - HTTP_PROXY: 

2025-04-16 11:26:23,451 - config - INFO - config.py:13 - HTTPS_PROXY: 

2025-04-16 11:26:23,453 - config - INFO - config.py:13 - AA_DONATOR_KEY: 

2025-04-16 11:26:23,455 - config - INFO - config.py:13 - FLASK_HOST: 0.0.0.0

2025-04-16 11:26:23,456 - config - INFO - config.py:13 - FLASK_PORT: 8084

2025-04-16 11:26:23,458 - config - INFO - config.py:13 - FLASK_DEBUG: False

2025-04-16 11:26:23,459 - config - INFO - config.py:13 - DEBUG: False

2025-04-16 11:26:23,461 - config - INFO - config.py:13 - LOG_LEVEL: INFO

2025-04-16 11:26:23,461 - config - INFO - config.py:13 - ENABLE_LOGGING: True

2025-04-16 11:26:23,462 - config - INFO - config.py:13 - MAIN_LOOP_SLEEP_TIME: 5

2025-04-16 11:26:23,465 - config - INFO - config.py:13 - DOCKERMODE: True

2025-04-16 11:26:23,466 - config - INFO - config.py:13 - USE_DOH: False

2025-04-16 11:26:23,467 - config - INFO - config.py:13 - BYPASS_RELEASE_INACTIVE_MIN: 5

2025-04-16 11:26:23,468 - config - INFO - config.py:13 - APP_ENV: prod

2025-04-16 11:26:23,469 - config - INFO - config.py:13 - LOG_FILE: /var/log/cwa-book-downloader/cwa-bookd-downloader.log

2025-04-16 11:26:23,470 - config - INFO - config.py:13 - USING_TOR: False

2025-04-16 11:26:23,511 - config - INFO - config.py:20 - BASE_DIR: /app

2025-04-16 11:26:23,515 - config - INFO - config.py:29 - STAT TMP_DIR: os.stat_result(st_mode=16877, st_ino=27407, st_dev=2050, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1744614026, st_mtime=1744706101, st_ctime=1744706101)

2025-04-16 11:26:23,517 - config - INFO - config.py:30 - STAT INGEST_DIR: os.stat_result(st_mode=16895, st_ino=27024, st_dev=2050, st_nlink=1, st_uid=0, st_gid=100, st_size=4096, st_atime=1744355496, st_mtime=1744706109, st_ctime=1744795284)

2025-04-16 11:26:23,517 - config - INFO - config.py:31 - CROSS_FILE_SYSTEM: False

2025-04-16 11:26:23,518 - config - INFO - config.py:51 - CUSTOM_DNS: []

2025-04-16 11:26:23,519 - config - INFO - config.py:57 - DOH_SERVER: 

2025-04-16 11:26:23,520 - config - INFO - config.py:65 - PROXIES: {}

2025-04-16 11:26:23,521 - config - INFO - config.py:75 - SUPPORTED_FORMATS: ['epub', 'mobi', 'azw3', 'fb2', 'djvu', 'cbz', 'cbr']

2025-04-16 11:26:28,536 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']

2025-04-16 11:26:30,895 - network - INFO - network.py:337 - AA_BASE_URL: https://annas-archive.org

2025-04-16 11:26:40,700 - backend - INFO - backend.py:162 - Starting download loop
```
The search bar shows: An error ocurred while searching...

My docker compose file is:

`services:
  calibre-web-automated-book-downloader-tor:
    container_name: calibre-downloader
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader-tor:latest
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: es,en
      USE_BOOK_TITLE: true
      FLASK_DEBUG: false
      ENABLE_TOR: true
      TZ: Europe/Madrid
      APP_ENV: prod
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /mnt/HAL/Libros/book-ingest:/cwa-book-ingest
      - /mnt/HAL/Libros/tmp:/tmp/cwa-book-downloader

    networks:
      - my-net

networks:
   my-net:
     name: my-net
     external: true	           
`

**Comment by janaxhell** [comment]
I've just noticed the same behavior and I don't use any VPN. I saw the container's icon showing as Unhealthy in Portainer, checked logs seeing nothing wrong, tried to download something and here it is the same error. Also the last "Waiting 40s before trying" is lying: after 6 minutes it was still there. 

```
Starting entrypoint script
Log file: /var/log//cwa-book-downloader/cwa-bd_entrypoint.log
Username for UID 0 is root
Changing ownership of /app to root:100
Changing ownership of /var/log/cwa-book-downloader to root:100
Changing ownership of /cwa-book-ingest to root:100
Verifying /tmp has enough space
Success: /tmp is writable
Running command: 'gunicorn -b 0.0.0.0:8084 app:app' as 'root' in 'prod' mode
[2025-04-16 20:24:43 +0000] [24] [INFO] Starting gunicorn 23.0.0
[2025-04-16 20:24:43 +0000] [24] [INFO] Listening at: http://0.0.0.0:8084 (24)
[2025-04-16 20:24:43 +0000] [24] [INFO] Using worker: sync
[2025-04-16 20:24:43 +0000] [31] [INFO] Booting worker with pid: 31
2025-04-16 20:24:44,150 - config - INFO - config.py:13 - os: <module 'os' from '/usr/local/lib/python3.10/os.py'>
2025-04-16 20:24:44,150 - config - INFO - config.py:13 - Path: <class 'pathlib.Path'>
2025-04-16 20:24:44,151 - config - INFO - config.py:13 - string_to_bool: <function string_to_bool at 0x7f0012625bd0>
2025-04-16 20:24:44,151 - config - INFO - config.py:13 - LOG_ROOT: /var/log
2025-04-16 20:24:44,151 - config - INFO - config.py:13 - LOG_DIR: /var/log/cwa-book-downloader
2025-04-16 20:24:44,151 - config - INFO - config.py:13 - TMP_DIR: /tmp/cwa-book-downloader
2025-04-16 20:24:44,151 - config - INFO - config.py:13 - INGEST_DIR: /cwa-book-ingest
2025-04-16 20:24:44,151 - config - INFO - config.py:13 - STATUS_TIMEOUT: 3600
2025-04-16 20:24:44,151 - config - INFO - config.py:13 - USE_BOOK_TITLE: False
2025-04-16 20:24:44,154 - config - INFO - config.py:13 - MAX_RETRY: 10
2025-04-16 20:24:44,154 - config - INFO - config.py:13 - DEFAULT_SLEEP: 5
2025-04-16 20:24:44,154 - config - INFO - config.py:13 - USE_CF_BYPASS: True
2025-04-16 20:24:44,154 - config - INFO - config.py:13 - HTTP_PROXY: 
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - HTTPS_PROXY: 
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - AA_DONATOR_KEY: 
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - FLASK_HOST: 0.0.0.0
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - FLASK_PORT: 8084
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - FLASK_DEBUG: False
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - DEBUG: False
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - LOG_LEVEL: INFO
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - ENABLE_LOGGING: True
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - MAIN_LOOP_SLEEP_TIME: 5
2025-04-16 20:24:44,155 - config - INFO - config.py:13 - DOCKERMODE: True
2025-04-16 20:24:44,156 - config - INFO - config.py:13 - USE_DOH: False
2025-04-16 20:24:44,156 - config - INFO - config.py:13 - BYPASS_RELEASE_INACTIVE_MIN: 5
2025-04-16 20:24:44,156 - config - INFO - config.py:13 - APP_ENV: prod
2025-04-16 20:24:44,156 - config - INFO - config.py:13 - LOG_FILE: /var/log/cwa-book-downloader/cwa-bookd-downloader.log
2025-04-16 20:24:44,156 - config - INFO - config.py:13 - USING_TOR: False
2025-04-16 20:24:44,157 - config - INFO - config.py:20 - BASE_DIR: /app
2025-04-16 20:24:44,160 - config - INFO - config.py:29 - STAT TMP_DIR: os.stat_result(st_mode=16877, st_ino=22970225, st_dev=74, st_nlink=2, st_uid=0, st_gid=0, st_size=4096, st_atime=1744835084, st_mtime=1744835084, st_ctime=1744835084)
2025-04-16 20:24:44,167 - config - INFO - config.py:30 - STAT INGEST_DIR: os.stat_result(st_mode=16895, st_ino=140041, st_dev=2082, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1744408094, st_mtime=1744408094, st_ctime=1744408094)
2025-04-16 20:24:44,168 - config - INFO - config.py:31 - CROSS_FILE_SYSTEM: True
2025-04-16 20:24:44,168 - config - INFO - config.py:51 - CUSTOM_DNS: []
2025-04-16 20:24:44,168 - config - INFO - config.py:57 - DOH_SERVER: 
2025-04-16 20:24:44,168 - config - INFO - config.py:65 - PROXIES: {}
2025-04-16 20:24:44,168 - config - INFO - config.py:75 - SUPPORTED_FORMATS: ['epub', 'mobi', 'azw3', 'fb2', 'djvu', 'cbz', 'cbr']
2025-04-16 20:24:45,262 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']
2025-04-16 20:24:45,674 - network - INFO - network.py:337 - AA_BASE_URL: https://annas-archive.org
2025-04-16 20:24:47,349 - backend - INFO - backend.py:164 - Starting download loop
2025-04-17 15:54:14,166 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=silvio%20garattini&lang=it
2025-04-17 15:54:47,984 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=la%20fioritura%20dei%20neuroni&lang=it
2025-04-17 15:55:00,205 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/md5/23220b8e22fcf3542805c6141f21c279
2025-04-17 15:55:06,299 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/md5/ca383d82db54c829c5f0385933a1de2c
2025-04-17 15:55:14,283 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/md5/23220b8e22fcf3542805c6141f21c279
2025-04-17 15:55:27,776 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/md5/23220b8e22fcf3542805c6141f21c279
2025-04-17 15:55:28,974 - backend - INFO - backend.py:68 - Book queued: La fioritura dei neuroni: Come far sbocciare la nostra intelligenza per tutta la vita
2025-04-17 15:55:30,231 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/slow_download/23220b8e22fcf3542805c6141f21c279/0/2
2025-04-17 15:55:30,285 - downloader - WARNING - downloader.py:64 - 403 detected for URL: https://annas-archive.org/slow_download/23220b8e22fcf3542805c6141f21c279/0/2. Should retry using cloudflare bypass.
2025-04-17 15:55:30,285 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: https://annas-archive.org/slow_download/23220b8e22fcf3542805c6141f21c279/0/2
2025-04-17 15:55:30,285 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:146 - SB_GET: https://annas-archive.org/slow_download/23220b8e22fcf3542805c6141f21c279/0/2
2025-04-17 15:55:30,285 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:180 - Getting driver...
2025-04-17 15:55:30,712 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:186 - Display started
2025-04-17 15:55:56,003 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 1 / 10
2025-04-17 15:55:56,003 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 0s before trying...
2025-04-17 15:56:13,512 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-17 15:56:13,845 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 2 / 10
2025-04-17 15:56:13,855 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 5s before trying...
2025-04-17 15:56:34,428 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-17 15:56:34,541 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 3 / 10
2025-04-17 15:56:34,543 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 10s before trying...
2025-04-17 15:56:59,824 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-17 15:56:59,876 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 4 / 10
2025-04-17 15:56:59,877 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 15s before trying...
2025-04-17 15:57:39,216 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-17 15:57:39,382 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 5 / 10
2025-04-17 15:57:39,383 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 20s before trying...
2025-04-17 15:58:30,037 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-17 15:58:30,094 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 6 / 10
2025-04-17 15:58:30,094 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 25s before trying...
2025-04-17 15:58:57,356 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-17 15:58:57,406 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 7 / 10
2025-04-17 15:58:57,407 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 30s before trying...
2025-04-17 15:59:28,464 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-17 15:59:28,546 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 8 / 10
2025-04-17 15:59:28,558 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 35s before trying...
2025-04-17 16:00:04,047 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-17 16:00:04,321 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 9 / 10
2025-04-17 16:00:04,324 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 40s before trying...

```

This is my compose:

```
services:
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: it
    ports:
      - "${FLASK_PORT:-8184}:${FLASK_PORT:-8084}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.94:${FLASK_PORT:-8184}/request/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/import/ebooks:/cwa-book-ingest

  cloudflarebypassforscraping:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: unless-stopped
networks:
  default:
    external:
      name: omv1
```

**Comment by calibrain** [comment]
Hi, could you update to use the latest docker-compose ? 
For example, we change the dropped the CLOUDFLARE_PROXY_URL, and are now not using cloudflarebypassforscraping image anymore.
The healthcheck also changed a bit
But in your case @barukh27  it seems that Cloudflare bypass is failing, maybe a blacklisted IP or something
(also, the waiting 40sec thing, it just means before retrying, trying itself can take a few minutes)

Could you retry using a VPN ? Or if you dont have access to one, you can use the TOR version
```
services:
  calibre-web-automated-book-downloader-tor:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader-tor:latest
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: it
      FLASK_DEBUG: false
      ENABLE_TOR: true
      APP_ENV: prod
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8184:8084
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/import/ebooks:/cwa-book-ingest
networks:
  default:
    external:
      name: omv1
```

**Comment by calibrain** [comment]
@barukh27 are there more logs from the server ? Or did it crash ? usually when the frontend gives such as message the server is not responding, do you have further logs ?

**Comment by janaxhell** [comment]
@calibrain Thanks for the compose, it works fine now. I don't have an external VPN (just Wireguard inside the fritz.box router pointing at my Pihole), so the tor version is perfect. I tried the same book that failed with previous build and it bypassed CF and downloaded immediately.

**Comment by preacher65** [comment]
Hi, I'm not sure if this is the same issue, or if I'm just doing something wrong... I can't get the CF bypasser to work at all. It worked a few builds ago, but I can't seem to find a way to revert to older builds. I've tried with and without VPN, and using two different VPN providers (Surfshark and ExpressVPN) via separate gluetun containers. Here's my current docker-compose file.
```
services:
  calibre-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: calibre-downloader
    labels:
      - "com.centurylinklabs.watchtower.scope=scheduled"
    volumes:
      - /volume1/data/calibre/upload:/cwa-book-ingest
      - /volume1/docker/appdata/calibre-downloader/log:/var/log/cwa-book-downloader
      - /volume1/docker/appdata/calibre-downloader/tmp:/tmp/cwa-book-downloader
    network_mode: "container:gluetun2"
#    networks:
#      - docker
#    ports:
#      - "8084:8084"
    environment:
      # If you change the FLASK_PORT, do not forget to change it in ports and healthcheck as well.
      - FLASK_PORT=8084
      - LOG_LEVEL=debug
      - BOOK_LANGUAGE=en
      - USE_BOOK_TITLE=true
      - FLASK_DEBUG=false
      - TZ=Europe/London
      - APP_ENV=prod
      - UID=1026
      - GID=101
    healthcheck:
      test: ["CMD", "pyrequests", "http://localhost:8084/request/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped


#networks:
#  docker:
#    name: docker
#    external: true
```
I get repeated retries from the CF bypasser as shown in the log snippet below:
```
2025-04-19 13:05:44,205 - downloader - DEBUG - downloader.py:34 - html_get_page: https://annas-archive.org/slow_download/b18f88dfcae6bccfec4d76cde83bbbb9/0/2, retry: 10, use_bypasser: False

2025-04-19 13:05:44,205 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/slow_download/b18f88dfcae6bccfec4d76cde83bbbb9/0/2

2025-04-19 13:05:44,328 - downloader - WARNING - downloader.py:64 - 403 detected for URL: https://annas-archive.org/slow_download/b18f88dfcae6bccfec4d76cde83bbbb9/0/2. Should retry using cloudflare bypass.

2025-04-19 13:05:44,328 - downloader - DEBUG - downloader.py:34 - html_get_page: https://annas-archive.org/slow_download/b18f88dfcae6bccfec4d76cde83bbbb9/0/2, retry: 9, use_bypasser: True

2025-04-19 13:05:44,329 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: https://annas-archive.org/slow_download/b18f88dfcae6bccfec4d76cde83bbbb9/0/2

2025-04-19 13:05:44,329 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:146 - SB_GET: https://annas-archive.org/slow_download/b18f88dfcae6bccfec4d76cde83bbbb9/0/2

2025-04-19 13:05:44,329 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:180 - Getting driver...

2025-04-19 13:05:54,609 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:186 - Display started

2025-04-19 13:06:33,241 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 1 / 10

2025-04-19 13:06:33,241 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 0s before trying...

2025-04-19 13:06:49,480 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.

2025-04-19 13:06:49,602 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 2 / 10

2025-04-19 13:06:49,602 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 5s before trying...

2025-04-19 13:07:11,019 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
```
I'm running all of this on a Synology NAS, if that's relevant. If there's any other info that could help, please let me know.

This is just a backup downloader for me, so I'm quite happy to wait and keep trying future builds, but I'm able to assist with any troubleshooting if that would be useful.

**Comment by preacher65** [comment]
Just to add that I also tried the TOR container, which I couldn't get to work at all. I thought that might be due to the Synology implementation of Docker, so haven't done much with that.

**Comment by calibrain** [comment]
Synology has some extra security around running NET_RAw and NET_ADMIN capabilities
I don't have one anymore, so I can't test it sorry :( 

Yeah, there is a bunch (probably way too much...) retries, but at some point it will give up and try alternatives (z-lib only lets you download 4-5 times per day, then it falls back on lib.gen which has only a small subset of books, etc.)

Can you download books on your browser normally ? Like on your normal browser, can you go through this URL : https://annas-archive.org/slow_download/23220b8e22fcf3542805c6141f21c279/0/2 ?

**Comment by preacher65** [comment]
Thanks for the reply.

> Synology has some extra security around running NET_RAw and NET_ADMIN
If all else fails, I'll do some research and try to get the TOR version running. However the standard image has worked for me before. Is there any enhanced logging I can enable to capture what the CF bypasser is doing?

> but at some point it will give up and try alternatives
It tried libgen first, I think. Then z-lib.

> an you download books on your browser normally ?
Yep, I get the Cloudflare "confirm you're a human", tick the box, and then get to the download page - and the download works.

Here's the full log in case it's useful:
https://gist.github.com/preacher65/1fbf4761db62ce5c007c2c5c63531dea#file-gistfile1-txt

**Comment by calibrain** [comment]
These logs are when using without TOR right ?
To skip completely cloudflare bypass (since it does not seem to be working for you anyway)
You could set `USE_CF_BYPASS: false`
This will just try z-lib and libgen, it should be much faster

**Comment by preacher65** [comment]
Yes, without TOR - I have an entirely separate compose that creates a different container for testing with TOR. I'll try to see what's needed to get that working on Synology.

Bypass definitely worked before, when the bypasser was a separate container. And I'm 98% certain I tested downloads after the cf bypasser was integrated.

I can see from my logs that the CF verification page doesn't appear to be detected, if the logs in the first post here are an indication of what I should expect.

As I stopped using CWA, the Book Downloader is really just a backup option for me. I don't want to take too much of your time on what could be an edge case, and not the same issue as others are reporting. Downloads are fine if I disable the CF bypass as above.

**Comment by calibrain** [comment]
So according to the logs, its failing to run the bypass, but it is detecting correctly the CF verification page.
The previous method using the separate container had a lot of issues, including no ARM compatible, and high CPU/Memory usage
Technically, this new method should also be stealthier...
But it seems on your specific system it's getting detected (it can be due to ISP, host spec, etc.)

I am always looking for more ways to bypass CF, so ill try a few things, but it is a hard problem
If I ever figure out a better way, I will ping you back here if you want to test it, but probably in the next few weeks

I will keep this issue open for tracking purposes !
Thank you

**Comment by preacher65** [comment]
I was initially running without VPN, and then tried through 2 different VPNs using gluetun (Surfshark, ExpressVPN), so I wouldn't expect it to be ISP blocking. Although it's possible both VPNs are blocked I guess, and I have a DNAT address from my ISP.

If you ever want anything tested, I'm more than happy to do so. But as I'm only using this tool as a backup, I can always just manually go to AA and find the books! :D Thanks so much for taking the time to reply.

**Comment by barukh27** [comment]
> [@barukh27](https://github.com/barukh27) are there more logs from the server ? Or did it crash ? usually when the frontend gives such as message the server is not responding, do you have further logs ?

Thank you for your answer. I run it in a RPi4 and, from time to time, while searching it crashes. I don't have more logs. Sorry.

**Comment by barukh27** [comment]
@calibrain 

Thanks, again, for your help. Now, I have it running behind gluetun. Same result.

`Starting entrypoint script
Log file: /var/log//cwa-book-downloader/cwa-bd_entrypoint.log
Build version: $(date +'%Y%m%d')-05744eb25619ca2d86391c2143083337f928c18f
Setting timezone to Europe/Madrid
Adding group 1000 with name appuser
Adding user 1000 with name appuser
Username for UID 1000 is appuser
Changing ownership of /app to appuser:1000
Changing ownership of /var/log/cwa-book-downloader to appuser:1000
Changing ownership of /cwa-book-ingest to appuser:1000
Changing ownership of /tmp/cwa-book-downloader to appuser:1000
Verifying /tmp has enough space
Success: /tmp is writable
Running command: 'gunicorn -t 300 -b 0.0.0.0:8084 app:app' as 'appuser' in 'prod' mode
[2025-04-20 10:05:27 +0200] [47] [INFO] Starting gunicorn 23.0.0
[2025-04-20 10:05:27 +0200] [47] [INFO] Listening at: http://0.0.0.0:8084 (47)
[2025-04-20 10:05:27 +0200] [47] [INFO] Using worker: sync
[2025-04-20 10:05:27 +0200] [48] [INFO] Booting worker with pid: 48
2025-04-20 10:05:28,108 - config - INFO - config.py:13 - os: <module 'os' from '/usr/local/lib/python3.10/os.py'>
2025-04-20 10:05:28,109 - config - INFO - config.py:13 - Path: <class 'pathlib.Path'>
2025-04-20 10:05:28,109 - config - INFO - config.py:13 - string_to_bool: <function string_to_bool at 0x7fb2b79c60>
2025-04-20 10:05:28,110 - config - INFO - config.py:13 - LOG_ROOT: /var/log
2025-04-20 10:05:28,111 - config - INFO - config.py:13 - LOG_DIR: /var/log/cwa-book-downloader
2025-04-20 10:05:28,112 - config - INFO - config.py:13 - TMP_DIR: /tmp/cwa-book-downloader
2025-04-20 10:05:28,113 - config - INFO - config.py:13 - INGEST_DIR: /cwa-book-ingest
2025-04-20 10:05:28,114 - config - INFO - config.py:13 - STATUS_TIMEOUT: 3600
2025-04-20 10:05:28,115 - config - INFO - config.py:13 - USE_BOOK_TITLE: True
2025-04-20 10:05:28,116 - config - INFO - config.py:13 - MAX_RETRY: 10
2025-04-20 10:05:28,116 - config - INFO - config.py:13 - DEFAULT_SLEEP: 5
2025-04-20 10:05:28,117 - config - INFO - config.py:13 - USE_CF_BYPASS: True
2025-04-20 10:05:28,118 - config - INFO - config.py:13 - HTTP_PROXY: 
2025-04-20 10:05:28,118 - config - INFO - config.py:13 - HTTPS_PROXY: 
2025-04-20 10:05:28,119 - config - INFO - config.py:13 - AA_DONATOR_KEY: 
2025-04-20 10:05:28,120 - config - INFO - config.py:13 - FLASK_HOST: 0.0.0.0
2025-04-20 10:05:28,120 - config - INFO - config.py:13 - FLASK_PORT: 8084
2025-04-20 10:05:28,121 - config - INFO - config.py:13 - FLASK_DEBUG: False
2025-04-20 10:05:28,122 - config - INFO - config.py:13 - DEBUG: False
2025-04-20 10:05:28,123 - config - INFO - config.py:13 - LOG_LEVEL: INFO
2025-04-20 10:05:28,123 - config - INFO - config.py:13 - ENABLE_LOGGING: True
2025-04-20 10:05:28,124 - config - INFO - config.py:13 - MAIN_LOOP_SLEEP_TIME: 5
2025-04-20 10:05:28,125 - config - INFO - config.py:13 - DOCKERMODE: True
2025-04-20 10:05:28,126 - config - INFO - config.py:13 - USE_DOH: False
2025-04-20 10:05:28,126 - config - INFO - config.py:13 - BYPASS_RELEASE_INACTIVE_MIN: 5
2025-04-20 10:05:28,127 - config - INFO - config.py:13 - APP_ENV: prod
2025-04-20 10:05:28,128 - config - INFO - config.py:13 - LOG_FILE: /var/log/cwa-book-downloader/cwa-bookd-downloader.log
2025-04-20 10:05:28,128 - config - INFO - config.py:13 - USING_TOR: False
2025-04-20 10:05:28,130 - config - INFO - config.py:20 - BASE_DIR: /app
2025-04-20 10:05:28,133 - config - INFO - config.py:29 - STAT TMP_DIR: os.stat_result(st_mode=16877, st_ino=27407, st_dev=2050, st_nlink=1, st_uid=1000, st_gid=1000, st_size=0, st_atime=1744614026, st_mtime=1744706101, st_ctime=1745136319)
2025-04-20 10:05:28,134 - config - INFO - config.py:30 - STAT INGEST_DIR: os.stat_result(st_mode=16895, st_ino=27024, st_dev=2050, st_nlink=1, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1744355496, st_mtime=1744706109, st_ctime=1745136319)
2025-04-20 10:05:28,134 - config - INFO - config.py:31 - CROSS_FILE_SYSTEM: False
2025-04-20 10:05:28,135 - config - INFO - config.py:51 - CUSTOM_DNS: []
2025-04-20 10:05:28,135 - config - INFO - config.py:57 - DOH_SERVER: 
2025-04-20 10:05:28,135 - config - INFO - config.py:65 - PROXIES: {}
2025-04-20 10:05:28,136 - config - INFO - config.py:75 - SUPPORTED_FORMATS: ['epub', 'mobi', 'azw3', 'fb2', 'djvu', 'cbz', 'cbr']
2025-04-20 10:05:29,244 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']
2025-04-20 10:05:29,561 - network - INFO - network.py:337 - AA_BASE_URL: https://annas-archive.org
2025-04-20 10:05:31,674 - backend - INFO - backend.py:164 - Starting download loop
2025-04-20 10:05:54,696 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=arde&lang=en&lang=es
2025-04-20 10:06:16,606 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=arde&lang=es
2025-04-20 10:06:25,772 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/md5/0eff0cb19d745ec883b4eda26ac6a87d
2025-04-20 10:06:27,925 - backend - INFO - backend.py:68 - Book queued: [erased]
2025-04-20 10:06:31,733 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/slow_download/0eff0cb19d745ec883b4eda26ac6a87d/0/2
2025-04-20 10:06:31,940 - downloader - WARNING - downloader.py:64 - 403 detected for URL: https://annas-archive.org/slow_download/0eff0cb19d745ec883b4eda26ac6a87d/0/2. Should retry using cloudflare bypass.
2025-04-20 10:06:31,942 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: https://annas-archive.org/slow_download/0eff0cb19d745ec883b4eda26ac6a87d/0/2
2025-04-20 10:06:31,943 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:146 - SB_GET: https://annas-archive.org/slow_download/0eff0cb19d745ec883b4eda26ac6a87d/0/2
2025-04-20 10:06:31,944 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:180 - Getting driver...
2025-04-20 10:06:34,455 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:186 - Display started
2025-04-20 10:07:14,145 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 1 / 10
2025-04-20 10:07:14,152 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 0s before trying...
2025-04-20 10:07:39,176 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:98 - Bypass failed.
2025-04-20 10:07:39,607 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:76 - Bypass attempt 2 / 10
2025-04-20 10:07:39,609 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:81 - Waiting 5s before trying...`

**Comment by calibrain** [comment]
Thank you for the new logs !
I actually just wrote a new method of generating logs for debugging, directly in the UI there is now a DEBUG button if you are using `DEBUG: true` environment in the compose
It also records the fake screen to show exactly what is happening
Could you try to download a book, and let it run for ~5minutes, then click on the DEBUG button in the UI and share with me the file ?

![Image](https://github.com/user-attachments/assets/16d044ff-1a94-46c7-b712-95ba952bf545)

![Image](https://github.com/user-attachments/assets/0852331d-3c68-49d7-91c9-36dec2596f33)

**Comment by preacher65** [comment]
Re. the TOR container on Synology, just in case it's relevant or useful:

The error message the container throws is
`iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: Invalid argument`

The Synology iptables version is iptables v1.8.3 (legacy)

I'm running the container as privileged, so I don't think it's a permissions error, possibly an iptables version mismatch?

Just thought this might be useful info.

**Comment by calibrain** [comment]
Thank you very much for the logs
Yeah it seems sinology is using legacy iptables, I downgraded the docker one to use the same (legacy is forward compatible and still widely supported anyway so it should be fine)
I just merged the change in #153 could you retry (in ~10min when the build will finish)

**Comment by barukh27** [comment]
> DEBUG: true

Should I disable CF bypasser? When enabled, after two attemps, the system crashes.

**Comment by preacher65** [comment]
> I just merged the change in https://github.com/calibrain/calibre-web-automated-book-downloader/pull/153 could you retry (in ~10min when the build will finish)

Thanks for trying, but it looks like the iptables version on Synology doesn't have the owner module?
Logs show
```
[*] Setting up iptables rules...
Warning: Extension owner revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.
```

**Comment by preacher65** [comment]
> Could you try to download a book, and let it run for ~5minutes, then click on the DEBUG button in the UI and share with me the file ?

Not sure if you received logs from others but I've just uploaded logs from the non-TOR container:
[https://1drv.ms/u/c/bff9a82d9b201410/EexyBoTDXfNBh6x8Cn6zMf4BNcKUswVeBQdBL2O__AZH6A?e=AhWPU9](url)

**Comment by calibrain** [comment]
> Thanks for trying, but it looks like the iptables version on Synology doesn't have the owner module? If I'm understanding correctly.
If using TOR, keep the CF Bypass
I just pushed another PR to try to fix TOR for your synology, let me know if it helps (#154)
I love how simple everything is on Synology, but I hate how difficult anything that is not "officially" supported becomes

> Not sure if you received logs from others but I've just uploaded logs from the non-TOR container:
Thank you very much for the logs, glad the gather log function is working as expected :)
I checked the logs, and its.. hard
It seems that CloudFlare is detecting the system to be a bot and is refusing the connection (by refreshing the captcha page)
I am looking in alternative bypass methods, but its hard

**Comment by iEdgir01** [comment]
Hi, Using the TOR Compose you posted earlier seems to have the same CF bypass issue.
I am not using a VPN, and Iw as getting a CF bypass error so i tried the TOR Compose and still no luck.

Compose:
`  calibre-web-automated-book-downloader-tor:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader-tor:latest
    container_name: calibre-web-automated-book-downloader
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      BOOK_LANGUAGE: en
      LOG_LEVEL: info
      ENABLE_TOR: true
      APP_ENV: prod
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8184:8084
    restart: unless-stopped
    volumes:
      - /mnt/fortress/books/downloads:/cwa-book-ingest`

Logs:

`2025-04-22 03:59:11,314 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=magician%20raymond&lang=en

2025-04-22 03:59:12,813 - downloader - WARNING - downloader.py:64 - 403 detected for URL: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=magician%20raymond&lang=en. Should retry using cloudflare bypass.

2025-04-22 03:59:12,814 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=magician%20raymond&lang=en

2025-04-22 03:59:12,814 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:156 - SB_GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=magician%20raymond&lang=en

2025-04-22 03:59:12,814 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:192 - Getting driver...

2025-04-22 03:59:13,025 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:198 - Display started

2025-04-22 03:59:36,732 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:97 - Bypass attempt 1 / 10

2025-04-22 03:59:36,735 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:102 - Waiting 0s before trying...

2025-04-22 03:59:46,912 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:162 - Bypass successful.

2025-04-22 03:59:47,335 - book_manager - WARNING - book_manager.py:76 - No results table found for query: magician raymond

2025-04-22 03:59:47,336 - backend - ERROR - logger.py:16 - Error searching books: No books found. Please try another query.

Traceback (most recent call last):

  File "/app/backend.py", line 34, in search_books

    books = book_manager.search_books(query, filters)

  File "/app/book_manager.py", line 77, in search_books

    raise Exception("No books found. Please try another query.")

Exception: No books found. Please try another query.

2025-04-22 04:00:13,327 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=raymond%20E%20Feist&lang=en

2025-04-22 04:00:14,656 - downloader - WARNING - downloader.py:64 - 403 detected for URL: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=raymond%20E%20Feist&lang=en. Should retry using cloudflare bypass.

2025-04-22 04:00:14,657 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=raymond%20E%20Feist&lang=en

2025-04-22 04:00:14,657 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:156 - SB_GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=raymond%20E%20Feist&lang=en

2025-04-22 04:00:14,658 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:192 - Getting driver...

2025-04-22 04:00:45,952 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:162 - Bypass successful.

2025-04-22 04:01:06,117 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=raymond%20E%20Feist%20Magician&lang=en

2025-04-22 04:01:07,538 - downloader - WARNING - downloader.py:64 - 403 detected for URL: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=raymond%20E%20Feist%20Magician&lang=en. Should retry using cloudflare bypass.

2025-04-22 04:01:07,542 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=raymond%20E%20Feist%20Magician&lang=en

2025-04-22 04:01:07,544 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:156 - SB_GET: https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=raymond%20E%20Feist%20Magician&lang=en

2025-04-22 04:01:07,545 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:192 - Getting driver...

2025-04-22 04:01:27,489 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:162 - Bypass successful.

2025-04-22 04:03:08,663 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/md5/f0951cc3d0d449f4a0b3acfe2a9f3510

2025-04-22 04:03:10,354 - downloader - WARNING - downloader.py:64 - 403 detected for URL: https://annas-archive.org/md5/f0951cc3d0d449f4a0b3acfe2a9f3510. Should retry using cloudflare bypass.

2025-04-22 04:03:10,355 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: https://annas-archive.org/md5/f0951cc3d0d449f4a0b3acfe2a9f3510

2025-04-22 04:03:10,355 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:156 - SB_GET: https://annas-archive.org/md5/f0951cc3d0d449f4a0b3acfe2a9f3510

2025-04-22 04:03:10,356 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:192 - Getting driver...

2025-04-22 04:03:21,515 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:162 - Bypass successful.

2025-04-22 04:03:21,991 - backend - INFO - backend.py:68 - Book queued: Magician Riftwar: The Riftwar Saga, Book 1

2025-04-22 04:03:26,738 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/slow_download/f0951cc3d0d449f4a0b3acfe2a9f3510/1/2

2025-04-22 04:03:28,391 - downloader - WARNING - downloader.py:64 - 403 detected for URL: https://annas-archive.org/slow_download/f0951cc3d0d449f4a0b3acfe2a9f3510/1/2. Should retry using cloudflare bypass.

2025-04-22 04:03:28,392 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: https://annas-archive.org/slow_download/f0951cc3d0d449f4a0b3acfe2a9f3510/1/2

2025-04-22 04:03:28,393 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:156 - SB_GET: https://annas-archive.org/slow_download/f0951cc3d0d449f4a0b3acfe2a9f3510/1/2

2025-04-22 04:03:28,393 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:192 - Getting driver...

2025-04-22 04:03:40,528 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:97 - Bypass attempt 1 / 10

2025-04-22 04:03:40,528 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:102 - Waiting 0s before trying...

2025-04-22 04:03:56,023 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:108 - Bypass failed.

2025-04-22 04:03:56,098 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:97 - Bypass attempt 2 / 10

2025-04-22 04:03:56,099 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:102 - Waiting 5s before trying...

2025-04-22 04:04:16,479 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:108 - Bypass failed.

2025-04-22 04:04:16,548 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:97 - Bypass attempt 3 / 10

2025-04-22 04:04:16,548 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:102 - Waiting 10s before trying...`

a question from my side, Does the TOR version take longer to produce results due to the TOR route?

**Comment by barukh27** [comment]
> 
> a question from my side, Does the TOR version take longer to produce results due to the TOR route? I am finding that the results take longer to load and the keyword searches need to be more accurate to produce results.

It appears that the "problem" is the bypasser itself. From my end, when I disable the CF bypasser everything works but it doesn't download from Anna's though. CF is a tricky wall.

**Comment by preacher65** [comment]
> I just pushed another PR to try to fix TOR for your synology, let me know if it helps (https://github.com/calibrain/calibre-web-automated-book-downloader/pull/154)

This time TOR seems to start, although cwa-bd-tor.log doesn't seem to get created where I'd expect it, or else doesn't persist past boot, so I've managed to grab some console output here:
```
Starting tor script
Log file: /var/log//cwa-book-downloader/cwa-bd_tor.log
Build version: 2025-04-21-88a95fe15ec8d172d1ef92db478f61ca904c02dd
[*] Installing Tor and dependencies...
[*] Writing Tor transparent proxy config...
[*] Setting up DNS...
[*] Starting Tor...
Starting tor daemon...done.
[*] Waiting for Tor to finish bootstrapping... (up to 5 minutes)
[✓] Tor is ready.
[*] Setting up iptables rules...
[✓] Transparent Tor routing enabled.
[*] Verifying Tor connectivity...
RESULT: {"IsTor":true,"IP":"199.195.253.180"}
[✓] Success! Traffic is routed through Tor. Current IP: 199.195.253.180
```
However I get no search results. Log bundle here:
[https://1drv.ms/u/c/bff9a82d9b201410/EUDNZRaPokNNjbGmd1g5HEABT3hIiUk-kpFIDNq9ucxX4Q?e=58LMvN](url)

> I love how simple everything is on Synology, but I hate how difficult anything that is not "officially" supported becomes

If I could go back and spend the money again, I'd probably build my own UNRAID type server. ;)

**Comment by calibrain** [comment]
@iEdgir01  yeah, TOR adds a huge delay to all routes, so search are slower, etc. 
I think AA has some logic to give less results if the connection is slow, which might explain why you need a more precise query ? (you can also just retry a few time)

Note that if you are using CF_BYPASS=false, you do not need TOR (and probably should not use it since it adds useless delays)

In your case here, the error is due to using `- USE_CF_BYPASS=false`
If using TOR, you must keep it to true (AA forces CF for even search when going through TOR)

Could you disable the flag and share the zip again ?

**Comment by preacher65** [comment]
So it was me that tried TOR but with CF bypassed. :D I've re-enabled CF bypass and tried again with TOR. I used Advanced Search with narrower parameters, instead of a quick and lazy search for everything by the author. The first search failed, but worked on a retry. Download still failsthough, seemingly at the CF bypass stage. Log bundle at this link:
https://1drv.ms/u/c/bff9a82d9b201410/ETpp_-xw3mhHmMH1pjxqINQB0JjwiBRcqjvnMhsI5QVNzw?e=MYuZVF

**Comment by calibrain** [comment]
Thank you so much for the report
I need to dig deeper into this
It seems that some kind of SSL issues that Cloudflare does not like...
I will dig deeper in it this weekend

**Comment by far2go** [comment]
Noticed your comment about not needing the giant cloudflare container and tried out the internal bypass without luck.  I'm wondering if there is something missing from the example compose files that I might need.  

`  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: cwa-downloader
    environment:
      - UID=${USER_ID}
      - GID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - FLASK_PORT=8084
      #- FLASK_DEBUG=false
      #- USING_TOR=true
      - LOG_LEVEL=info
      - APP_ENV=prod
      - INGEST_DIR=/cwa-book-ingest
      - BOOK_LANGUAGE=en
      - USE_BOOK_TITLE=true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${DATA_ROOT}/cwa-ingest:/cwa-book-ingest
    restart: unless-stopped
    ports:
      - '8084:8084'`

```
cwa-downloader 2025-04-26 12:06:09,824 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:108 - Bypass failed.
```

**Comment by calibrain** [comment]
You dont need the cap_add stuff if you are not running the tor container
Could you run with DEBUG=true ?
The UI will have a button to generate a bug report and could you share that zip file with me after ?
Thank you

**Comment by far2go** [comment]
[cwa-book-downloader-debug_BUILD-2025-04-27-457351fa0b3a602d545b63f1de7169efbb0dd3cb_20250427-170931.zip](https://github.com/user-attachments/files/19932475/cwa-book-downloader-debug_BUILD-2025-04-27-457351fa0b3a602d545b63f1de7169efbb0dd3cb_20250427-170931.zip)

**Comment by calibrain** [comment]
Thank you so much for the report !
I looked into it, and it seems that Cloudflare is detecting the automation, and I am not sure how to bypass it for now
I will dig a bit deeper into it, but I wont have any solution short term, other than just not using cloduflare (USE_CF_BYPASS = false), this will make use of alternative libraries such as zlib or libgen, but they might not have all the books you need / want

**Comment by andresatierf** [comment]
@calibrain would it be possible to add support for [`flaresolverr`](https://github.com/FlareSolverr/FlareSolverr) or [`byparr`](https://github.com/ThePhaseless/Byparr/)? would that help with this situation? I am also running into problems with this

**Comment by calibrain** [comment]
The tech behind cwa-bd cloudflare bypasser is very similar to flaresolverr, (and the exact same as byparr actually, I jsut checked their source code)

**Comment by gilbrotheraway** [comment]
> Thank you so much for the report ! I looked into it, and it seems that Cloudflare is detecting the automation, and I am not sure how to bypass it for now I will dig a bit deeper into it, but I wont have any solution short term, other than just not using cloduflare (USE_CF_BYPASS = false), this will make use of alternative libraries such as zlib or libgen, but they might not have all the books you need / want

here it keeps trying annasarchive when disabling CF bypass what's going on?

**Comment by calibrain** [comment]
Could you retry ?
I added some changes that might help now

**Comment by preacher65** [comment]
<del>Worked for me!!! Do you want any logs?</del>

<del>Hang on, I might not have been using the bypasser, sorry let me check compose yml and re-test</del>

Oops, sorry! I got too excited, LOL, and didn't check my environment properly. I had USE_CF_BYPASS=false, so it was downloading from libgen. Debug file to follow. This was outside of VPN.
For me at least, it's still having issues. Obviously can't speak for others!
```
2025-07-30 22:56:45,950 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:97 - Bypass attempt 1 / 10
2025-07-30 22:56:45,950 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:102 - Waiting 0s before trying...
2025-07-30 22:57:03,284 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:108 - Bypass failed.
2025-07-30 22:57:03,414 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:97 - Bypass attempt 2 / 10
2025-07-30 22:57:03,417 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:102 - Waiting 5s before trying...
2025-07-30 22:57:24,133 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:108 - Bypass failed.
```
Edit: debug file
https://1drv.ms/u/c/bff9a82d9b201410/EVrd1VEjRdhBoEbylRYWZfcBg_3kTk5_vwz9MYXRyBbwOw?e=hhhjis

**Comment by mathisgauthey** [comment]
> Could you retry ? I added some changes that might help now

On my end, with `20250730` docker image, I still get issues. It tries 10 times before reverting to something else than Anna's.

EDIT: Fixed it with the following env variables I got from [an answer](https://github.com/calibrain/calibre-web-automated-book-downloader/issues/182#issuecomment-3137458144) in #182 

```
environment:
  - CUSTOM_DNS=cloudflare
  - USE_DOH=true
```

**Comment by gilbrotheraway** [comment]
> > Could you retry ? I added some changes that might help now
> 
> On my end, with `20250730` docker image, I still get issues. It tries 10 times before reverting to something else than Anna's.
> 
> EDIT: Fixed it with the following env variables I got from [an answer](https://github.com/calibrain/calibre-web-automated-book-downloader/issues/182#issuecomment-3137458144) in [#182](https://github.com/calibrain/calibre-web-automated-book-downloader/issues/182)
> 
> ```
> environment:
>   - CUSTOM_DNS=cloudflare
>   - USE_DOH=true
> ```

same here @calibrain 
i was using a local unbound DNS instance before
now it works(without anna's archive)

**Comment by Giorox** [comment]
So, with:
```
environment:
      USE_DOH: true
      CUSTOM_DNS: cloudflare
      USE_CF_BYPASS: false
```

I get inconsistent results downloading from z-lib/libgen etc, but it works, Anna's Archive simply will not work (by setting `USE_CF_BYPASS` to `true`). Just my 2 cents, thanks to @VinnyG9 and @mathisgauthey

**Comment by calibrain** [comment]
This might be an issue with the ISP ?
Usually when forcing DOH its because your ISP tries to block access to these website 
(they sometimes also try to block IP, so I guess thats why results are inconsistent ?)

DOH tries to hide the full request from your ISP, including the website domain
