### ISSUE TITLE
[BUG] Cloudflare check failling

### ISSUE THREAD

**Issue by raaphhh** [calibrain/calibre-web-automated-book-downloader#226]
## Bug Description
When trying to download a book, it's stuck on the 'downloading status' and is failing the cloudflare check (cfr [this message](https://github.com/calibrain/calibre-web-automated-book-downloader/issues/209#issuecomment-3192404114))

## Steps To Reproduce
1. Download a book
2. Look at the Download Status, it's stuck in 'downloading'
3. Look at the logs

## Expected Behavior
At some point the status should go from 'downloading' to 'downloaded' and the book should be available

## Debug Information
**Important**: Please enable debug mode before submitting a bug report by setting the environment variable:
```
DEBUG=true
```

When running in debug mode, a DEBUG button will appear in the interface. Please click this button to generate a debug zip file and attach it to this issue.

[cwa-book-downloader-debug_BUILD-2025-08-06-86c642d8748b29c143ec9a0192bc6277ce76a817_20250819-085008.zip](https://github.com/user-attachments/files/21849872/cwa-book-downloader-debug_BUILD-2025-08-06-86c642d8748b29c143ec9a0192bc6277ce76a817_20250819-085008.zip)

## Environment Information
- BASE OS: Synology NAS via docker-compose

## docker-compose
```yml
  calibre-web-dl:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader
    container_name: calibre-web-dl
    environment:
      - FLASK_PORT=8084
      - LOG_LEVEL=info
      - DEBUG=true
      - BOOK_LANGUAGE=en
      - INGEST_DIR=/cwa-book-ingest
      - USE_BOOK_TITLE=true
      - FLASK_DEBUG=false
      - APP_ENV=prod
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
    ports:
      - 8072:8084
    restart: unless-stopped
    volumes:
      # This is where the books will be downloaded to, usually it would be 
      # the same as whatever you gave in "calibre-web-automated"
      - ${DOCKER_APPDATA_PATH}/calibre-web-dl:/cwa-book-downloader 
      - ${DOWNLOAD_PATH}/cwa_ingest:/cwa-book-ingest
    networks:
      - main

networks:
  main:
    external: true
```

## Additional Context
When running in debug mode, the book status is not stuck in 'downloading' and eventually it when to 'error' state

**Comment by calibrain** [comment]
Could you retry and update with the latest release ?
`docker pull ghcr.io/calibrain/calibre-web-automated-book-downloader:latest`

**Comment by roadkingvrod** [comment]
@calibrain , that fixed it for me. Thanks!

**Comment by raphhgg** [comment]
> Could you retry and update with the latest release ? `docker pull ghcr.io/calibrain/calibre-web-automated-book-downloader:latest`

With the `:latest` image, I can't even start the container anymore.

[raphh-logs.txt](https://github.com/user-attachments/files/21885996/raphh-logs.txt)

**Comment by calibrain** [comment]
@raaphhh  there is a bug in the container tagging
Follow #234 
Should be fixed in ~1-2h

**Comment by NinjaCreeper810** [comment]
The update fixed not being able to run the container. But I am still getting the original error that the ticket was opened for. Cloudflare bypass fails repeatedly and loops trying to download a book indefinitely

(Also calibrain Ive been lurking in the issues section for a couple days and I wanna say thank you for how much you have been doing for all of us. I can only imagine how stressful it may have been. Is there any way someone like myself can support the project?)

**Comment by Glennza1962** [comment]
I have noticed that it will go into a cloudflare loop but never seems to try welib. I thought that was meant to be used as backup?

**Comment by eddiewilliams** [comment]
For me It tries welib first, returns 403 forbidden and then cloudflare loops until I restart the container.

EDIT: To clarify, when I try it does what bheim777 described. It states 'Bypass successful' for welib, the book gets queued, returns 403 and then cloudflare loops.

**Comment by bheim777** [comment]
strange enough the logs show a successful cloudfare bypass for welib for me, he even says he queues the download, then no error, Just a switch to AA and starting the cloudfare bypass infinte loop of death until it switches to libgen and finally errors out. 
Switched out identifiable info for X. Tried out all dns servers with and with DOH true or false. 

```
Starting entrypoint script
Log file: /var/log//cwa-book-downloader/cwa-bd_entrypoint.log
Build version: 2025-08-21-5f6a81d97d16856ba0a9a6acf47107c54ed225c0
Setting timezone to X/X
Username for UID 0 is root
Changing ownership of /app to root:100
Changing ownership of /var/log/cwa-book-downloader to root:100
Changing ownership of /tmp/cwa-book-downloader to root:100
Test write to /cwa-book-ingest by root: true
Folder /cwa-book-ingest is writable, no need to change ownership
Test write to /cwa-book-ingest by root: true
Verifying /tmp has enough space
Success: /tmp is writable
Running command: 'gunicorn -t 300 -b 0.0.0.0:8084 app:app' as 'root' in 'prod' mode
[2025-08-21 14:07:40 +0200] [52] [INFO] Starting gunicorn 23.0.0
[2025-08-21 14:07:40 +0200] [52] [INFO] Listening at: [http://0.0.0.0:8084⁠](http://0.0.0.0:8084/) (52)
[2025-08-21 14:07:40 +0200] [52] [INFO] Using worker: sync
[2025-08-21 14:07:40 +0200] [61] [INFO] Booting worker with pid: 61
2025-08-21 14:07:40,701 - config - INFO - config.py:15 - os: <module 'os' from '/usr/local/lib/python3.10/os.py'>
2025-08-21 14:07:40,703 - config - INFO - config.py:15 - Path: <class 'pathlib.Path'>
2025-08-21 14:07:40,703 - config - INFO - config.py:15 - string_to_bool: <function string_to_bool at 0x7a6e1385e8c0>
2025-08-21 14:07:40,703 - config - INFO - config.py:15 - CWA_DB: /config/app.db
2025-08-21 14:07:40,704 - config - INFO - config.py:15 - CWA_DB_PATH: /config/app.db
2025-08-21 14:07:40,704 - config - INFO - config.py:15 - LOG_ROOT: /var/log
2025-08-21 14:07:40,704 - config - INFO - config.py:15 - LOG_DIR: /var/log/cwa-book-downloader
2025-08-21 14:07:40,704 - config - INFO - config.py:15 - TMP_DIR: /tmp/cwa-book-downloader
2025-08-21 14:07:40,704 - config - INFO - config.py:15 - INGEST_DIR: /cwa-book-ingest
2025-08-21 14:07:40,704 - config - INFO - config.py:15 - STATUS_TIMEOUT: 3600
2025-08-21 14:07:40,705 - config - INFO - config.py:15 - USE_BOOK_TITLE: True
2025-08-21 14:07:40,705 - config - INFO - config.py:15 - MAX_RETRY: 10
2025-08-21 14:07:40,705 - config - INFO - config.py:15 - DEFAULT_SLEEP: 5
2025-08-21 14:07:40,705 - config - INFO - config.py:15 - USE_CF_BYPASS: True
2025-08-21 14:07:40,706 - config - INFO - config.py:15 - HTTP_PROXY: 
2025-08-21 14:07:40,706 - config - INFO - config.py:15 - HTTPS_PROXY: 
2025-08-21 14:07:40,707 - config - INFO - config.py:15 - AA_DONATOR_KEY: 
2025-08-21 14:07:40,707 - config - INFO - config.py:15 - FLASK_HOST: 0.0.0.0
2025-08-21 14:07:40,707 - config - INFO - config.py:15 - FLASK_PORT: 8084
2025-08-21 14:07:40,707 - config - INFO - config.py:15 - DEBUG: False
2025-08-21 14:07:40,708 - config - INFO - config.py:15 - LOG_LEVEL: INFO
2025-08-21 14:07:40,708 - config - INFO - config.py:15 - ENABLE_LOGGING: True
2025-08-21 14:07:40,708 - config - INFO - config.py:15 - MAIN_LOOP_SLEEP_TIME: 5
2025-08-21 14:07:40,709 - config - INFO - config.py:15 - DOCKERMODE: True
2025-08-21 14:07:40,709 - config - INFO - config.py:15 - USE_DOH: False
2025-08-21 14:07:40,709 - config - INFO - config.py:15 - BYPASS_RELEASE_INACTIVE_MIN: 5
2025-08-21 14:07:40,710 - config - INFO - config.py:15 - APP_ENV: prod
2025-08-21 14:07:40,710 - config - INFO - config.py:15 - LOG_FILE: /var/log/cwa-book-downloader/cwa-book-downloader.log
2025-08-21 14:07:40,710 - config - INFO - config.py:15 - USING_TOR: False
2025-08-21 14:07:40,711 - config - INFO - config.py:22 - BASE_DIR: /app
2025-08-21 14:07:40,715 - config - INFO - config.py:31 - STAT TMP_DIR: os.stat_result(st_mode=16877, st_ino=148634, st_dev=158, st_nlink=2, st_uid=0, st_gid=100, st_size=4096, st_atime=1755778052, st_mtime=1755778052, st_ctime=1755778052)
2025-08-21 14:07:40,717 - config - INFO - config.py:32 - STAT INGEST_DIR: os.stat_result(st_mode=16895, st_ino=562949953657645, st_dev=71, st_nlink=1, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1755778054, st_mtime=1755778054, st_ctime=1755778054)
2025-08-21 14:07:40,718 - config - INFO - config.py:33 - CROSS_FILE_SYSTEM: True
2025-08-21 14:07:40,719 - config - INFO - config.py:53 - CUSTOM_DNS: ['8.8.8.8', '8.8.4.4', '2001:4860:4860::8888', '2001:4860:4860::8844']
2025-08-21 14:07:40,719 - config - INFO - config.py:59 - DOH_SERVER: 
2025-08-21 14:07:40,720 - config - INFO - config.py:67 - PROXIES: {}
2025-08-21 14:07:40,720 - config - INFO - config.py:77 - SUPPORTED_FORMATS: ['epub', 'mobi', 'azw3', 'fb2', 'djvu', 'cbz', 'cbr']
2025-08-21 14:07:41,376 - network - INFO - network.py:309 - Custom DNS resolver successfully configured and activated
2025-08-21 14:07:41,377 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']
2025-08-21 14:07:41,567 - network - INFO - network.py:337 - AA_BASE_URL: [https://annas-archive.org⁠](https://annas-archive.org/)
2025-08-21 14:07:42,798 - backend - INFO - backend.py:159 - Starting download loop
2025-08-21 14:07:43,090 - app - INFO - app.py:375 - Authentication successful for user X
2025-08-21 14:07:43,840 - app - INFO - app.py:375 - Authentication successful for user X
2025-08-21 14:08:18,390 - app - INFO - app.py:375 - Authentication successful for user X
2025-08-21 14:08:18,392 - downloader - INFO - downloader.py:44 - GET: [https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=X=en⁠](https://annas-archive.org/search?index=&page=1&display=table&acc=aa_download&acc=external_download&ext=epub&ext=mobi&ext=azw3&ext=fb2&ext=djvu&ext=cbz&ext=cbr&q=X=en)
2025-08-21 14:08:43,832 - app - INFO - app.py:375 - Authentication successful for user X
2025-08-21 14:09:43,860 - app - INFO - app.py:375 - Authentication successful for user X
2025-08-21 14:10:02,693 - app - INFO - app.py:375 - Authentication successful for user X
2025-08-21 14:10:02,694 - downloader - INFO - downloader.py:44 - GET: [https://annas-archive.org/md5/X](https://annas-archive.org/md5/X)
2025-08-21 14:10:04,202 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: [https://welib.org/md5/X](https://welib.org/md5/X)
2025-08-21 14:10:04,203 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:162 - SB_GET: [https://welib.org/md5/X](https://welib.org/md5/X)
2025-08-21 14:10:04,203 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:198 - Getting driver...
2025-08-21 14:10:04,370 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:204 - Display started
2025-08-21 14:10:29,716 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:168 - Bypass successful.
2025-08-21 14:10:29,990 - app - INFO - app.py:375 - Authentication successful for user X
2025-08-21 14:10:29,991 - downloader - INFO - downloader.py:44 - GET: [https://annas-archive.org/md5/X](https://annas-archive.org/md5/X)
2025-08-21 14:10:31,512 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: [https://welib.org/md5/X](https://welib.org/md5/X)
2025-08-21 14:10:31,513 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:162 - SB_GET: [https://welib.org/md5/X](https://welib.org/md5/X)
2025-08-21 14:10:31,514 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:198 - Getting driver...
2025-08-21 14:10:42,304 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:168 - Bypass successful.
2025-08-21 14:10:42,326 - backend - INFO - backend.py:68 - Book queued: X
2025-08-21 14:10:42,587 - app - INFO - app.py:375 - Authentication successful for user x
2025-08-21 14:10:43,861 - app - INFO - app.py:375 - Authentication successful for user x
2025-08-21 14:10:47,086 - downloader - INFO - downloader.py:44 - GET: [https://annas-archive.org/slow_download/x/1/2⁠](https://annas-archive.org/slow_download/x/1/2)
2025-08-21 14:10:47,166 - downloader - WARNING - downloader.py:64 - 403 detected for URL: [https://annas-archive.org/slow_download/x/1/2.⁠](https://annas-archive.org/slow_download/x/1/2.) Should retry using cloudflare bypass.
2025-08-21 14:10:47,166 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: [https://annas-archive.org/slow_download/x/1/2⁠](https://annas-archive.org/slow_download/x/1/2)
2025-08-21 14:10:47,167 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:162 - SB_GET: [https://annas-archive.org/slow_download/x/1/2⁠](https://annas-archive.org/slow_download/x/1/2)
2025-08-21 14:10:47,167 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:198 - Getting driver...
2025-08-21 14:10:57,746 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:168 - Bypass successful.
2025-08-21 14:10:57,756 - downloader - INFO - downloader.py:44 - GET: [https://annas-archive.org/slow_download/x/0/2⁠](https://annas-archive.org/slow_download/x/0/2)
2025-08-21 14:10:57,852 - downloader - WARNING - downloader.py:64 - 403 detected for URL: [https://annas-archive.org/slow_download/x/0/2.⁠](https://annas-archive.org/slow_download/x/0/2.) Should retry using cloudflare bypass.
2025-08-21 14:10:57,853 - downloader - INFO - downloader.py:36 - GET Using Cloudflare Bypasser for: [https://annas-archive.org/slow_download/xx/0/2⁠](https://annas-archive.org/slow_download/x/0/2)
2025-08-21 14:10:57,853 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:162 - SB_GET: [https://annas-archive.org/slow_download/x/0/2⁠](https://annas-archive.org/slow_download/x/0/2)
2025-08-21 14:10:57,854 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:198 - Getting driver...
2025-08-21 14:11:08,418 - cloudflare_bypasser - INFO - cloudflare_bypasser.py:168 - Bypass successful.
2025-08-21 14:11:08,433 - downloader - INFO - downloader.py:44 - GET: [https://libgen.bz/ads.php?md5=x](https://libgen.bz/ads.php?md5=x)
2025-08-21 14:11:11,721 - downloader - WARNING - downloader.py:68 - Retrying GET [https://libgen.bz/ads.php?md5=x](https://libgen.bz/ads.php?md5=x) in 5 seconds due to error: 523 Server Error: <none> for url: [https://libgen.bz/ads.php?md5=x](https://libgen.bz/ads.php?md5=x)
2025-08-21 14:11:16,726 - downloader - INFO - downloader.py:44 - GET: [https://libgen.bz/ads.php?md5=x](https://libgen.bz/ads.php?md5=x)

```

**Comment by NinjaCreeper810** [comment]
My logs are identical to bhiem, it succeeds on welib then goes to AA

**Comment by calibrain** [comment]
So while its not a bug, I can understand the confusion

The flow goes as such :
Search on AA
Find all links from AA
Using the MD5, find all links from welib
Try to download from libgen
If fail try to download from no wait AA
if fail try to download from libgen
If fail try to download from slow wait AA

And in the `Using the MD5, find all links from welib` step, we use Cloudflare Bypasser to look up the welib URL

The logic here is that the AA slow no wait files are still faster than welib download, since those have 300-600sec wait time for each download

**Comment by Glennza1962** [comment]
I have noticed that libgen.bz is dead. Don't know if this is temporary? .la and .li are working. Worth changing over?

**Comment by Glennza1962** [comment]
I set CF Bypass to "false", just to show   

 During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/downloader.py", line 46, in html_get_page
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://z-lib.fm/md5/f924904a91229ac544dc41b14058612e
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/downloader.py", line 46, in html_get_page
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://z-lib.fm/md5/f924904a91229ac544dc41b14058612e
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/downloader.py", line 46, in html_get_page
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://z-lib.fm/md5/f924904a91229ac544dc41b14058612e
2025-08-23 08:04:17,202 - backend - ERROR - logger.py:16 - Error downloading book: Unkown error downloading book
Traceback (most recent call last):
  File "/app/backend.py", line 134, in _download_book
    raise Exception("Unkown error downloading book")
Exception: Unkown error downloading book
2025-08-23 08:04:17,203 - backend - INFO - backend.py:178 - Book f924904a91229ac544dc41b14058612e download failed
[2025-08-23 08:06:07 +1000] [62] [INFO] Worker exiting (pid: 62)
[2025-08-23 08:06:07 +1000] [61] [INFO] Handling signal: term
[2025-08-23 08:06:07 +1000] [61] [INFO] Shutting down: Master
Starting entrypoint script
Log file: /var/log//cwa-book-downloader/cwa-bd_entrypoint.log
Build version: 2025-08-21-5f6a81d97d16856ba0a9a6acf47107c54ed225c0
Setting timezone to Australia/Brisbane
Username for UID 1000 is appuser
Changing ownership of /app to appuser:1000
Changing ownership of /var/log/cwa-book-downloader to appuser:1000
Changing ownership of /tmp/cwa-book-downloader to appuser:1000
Test write to /cwa-book-ingest by appuser: true
Folder /cwa-book-ingest is writable, no need to change ownership
Test write to /cwa-book-ingest by appuser: true
Verifying /tmp has enough space
Success: /tmp is writable
Running command: 'gunicorn -t 300 -b 0.0.0.0:8084 app:app' as 'appuser' in 'prod' mode
[2025-08-23 08:06:10 +1000] [52] [INFO] Starting gunicorn 23.0.0
[2025-08-23 08:06:10 +1000] [52] [INFO] Listening at: http://0.0.0.0:8084 (52)
[2025-08-23 08:06:10 +1000] [52] [INFO] Using worker: sync
[2025-08-23 08:06:10 +1000] [53] [INFO] Booting worker with pid: 53
2025-08-23 08:06:10,434 - config - INFO - config.py:15 - os: <module 'os' from '/usr/local/lib/python3.10/os.py'>
2025-08-23 08:06:10,434 - config - INFO - config.py:15 - Path: <class 'pathlib.Path'>
2025-08-23 08:06:10,434 - config - INFO - config.py:15 - string_to_bool: <function string_to_bool at 0x7622af9128c0>
2025-08-23 08:06:10,434 - config - INFO - config.py:15 - CWA_DB: None
2025-08-23 08:06:10,434 - config - INFO - config.py:15 - CWA_DB_PATH: None
2025-08-23 08:06:10,434 - config - INFO - config.py:15 - LOG_ROOT: /var/log
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - LOG_DIR: /var/log/cwa-book-downloader
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - TMP_DIR: /tmp/cwa-book-downloader
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - INGEST_DIR: /cwa-book-ingest
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - STATUS_TIMEOUT: 3600
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - USE_BOOK_TITLE: True
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - MAX_RETRY: 10
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - DEFAULT_SLEEP: 5
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - USE_CF_BYPASS: False
2025-08-23 08:06:10,435 - config - INFO - config.py:15 - HTTP_PROXY: 
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - HTTPS_PROXY: 
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - AA_DONATOR_KEY: 
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - FLASK_HOST: 0.0.0.0
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - FLASK_PORT: 8084
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - DEBUG: False
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - LOG_LEVEL: INFO
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - ENABLE_LOGGING: True
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - MAIN_LOOP_SLEEP_TIME: 5
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - DOCKERMODE: True
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - USE_DOH: False
2025-08-23 08:06:10,436 - config - INFO - config.py:15 - BYPASS_RELEASE_INACTIVE_MIN: 5
2025-08-23 08:06:10,437 - config - INFO - config.py:15 - APP_ENV: prod
2025-08-23 08:06:10,437 - config - INFO - config.py:15 - LOG_FILE: /var/log/cwa-book-downloader/cwa-book-downloader.log
2025-08-23 08:06:10,437 - config - INFO - config.py:15 - USING_TOR: False
2025-08-23 08:06:10,437 - config - INFO - config.py:22 - BASE_DIR: /app
2025-08-23 08:06:10,437 - config - INFO - config.py:31 - STAT TMP_DIR: os.stat_result(st_mode=16877, st_ino=2762501, st_dev=76, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1755900367, st_mtime=1755899860, st_ctime=1755900367)
2025-08-23 08:06:10,438 - config - INFO - config.py:32 - STAT INGEST_DIR: os.stat_result(st_mode=16895, st_ino=1056282, st_dev=2050, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1755825244, st_mtime=1755900367, st_ctime=1755900367)
2025-08-23 08:06:10,438 - config - INFO - config.py:33 - CROSS_FILE_SYSTEM: True
2025-08-23 08:06:10,438 - config - INFO - config.py:53 - CUSTOM_DNS: []
2025-08-23 08:06:10,438 - config - INFO - config.py:59 - DOH_SERVER: 
2025-08-23 08:06:10,438 - config - INFO - config.py:67 - PROXIES: {}
2025-08-23 08:06:10,438 - config - INFO - config.py:77 - SUPPORTED_FORMATS: ['epub']
2025-08-23 08:06:10,729 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']
2025-08-23 08:06:11,381 - network - INFO - network.py:337 - AA_BASE_URL: https://annas-archive.org
2025-08-23 08:06:11,391 - backend - INFO - backend.py:159 - Starting download loop
2025-08-23 08:06:14,906 - downloader - INFO - downloader.py:44 - GET: https://annas-archive.org/md5/f924904a91229ac544dc41b14058612e
2025-08-23 08:06:17,081 - backend - INFO - backend.py:68 - Book queued: Animal Farm
2025-08-23 08:06:21,400 - downloader - INFO - downloader.py:44 - GET: https://libgen.bz/ads.php?md5=f924904a91229ac544dc41b14058612e
2025-08-23 08:06:41,389 - downloader - WARNING - downloader.py:68 - Retrying GET https://libgen.bz/ads.php?md5=f924904a91229ac544dc41b14058612e in 5 seconds due to error: 522 Server Error: <none> for url: https://libgen.bz/ads.php?md5=f924904a91229ac544dc41b14058612e
2025-08-23 08:06:46,395 - downloader - INFO - downloader.py:44 - GET: https://libgen.bz/ads.php?md5=f924904a91229ac544dc41b14058612e

2025-08-23 08:06:49,385 - downloader - WARNING - downloader.py:68 - Retrying GET https://libgen.bz/ads.php?md5=f924904a91229ac544dc41b14058612e in 10 seconds due to error: 523 Server Error: <none> for url: https://libgen.bz/ads.php?md5=f924904a91229ac544dc41b14058612e

**Comment by calibrain** [comment]
Ya libgen.bz is dead, will update soon with a redirect to proper alternative

**Comment by calibrain** [comment]
I just pushed a new flag you can use
`PRIORITIZE_WELIB` if set to `true` it will download from welib before trying from AA
Build is ongoing, it usually takes ~1h (Progress : https://github.com/calibrain/calibre-web-automated-book-downloader/actions/runs/17167213710 )

Once the build is done, you can switch from `:latest` to `:dev` to try it out !

**Comment by NinjaCreeper810** [comment]
Thank you, using that tag fixed the issue for me!
