### ISSUE TITLE
[BUG] Docker doesn't start anymore

### ISSUE THREAD

**Issue by nodiaque** [calibrain/calibre-web-automated-book-downloader#227]
## Bug Description
Start and stop, error in log:

```
[2025-08-19 07:19:58 -0400] [52] [INFO] Starting gunicorn 23.0.0
[2025-08-19 07:19:58 -0400] [52] [INFO] Listening at: http://0.0.0.0:8084 (52)
[2025-08-19 07:19:58 -0400] [52] [INFO] Using worker: sync
[2025-08-19 07:19:58 -0400] [53] [INFO] Booting worker with pid: 53
[2025-08-19 07:19:59 -0400] [53] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app.py", line 17, in <module>
    import backend
  File "/app/backend.py", line 14, in <module>
    import book_manager
  File "/app/book_manager.py", line 9, in <module>
    import downloader
  File "/app/downloader.py", line 16, in <module>
    import cloudflare_bypasser
  File "/app/cloudflare_bypasser.py", line 13, in <module>
    from seleniumbase import Driver
ImportError: cannot import name 'Driver' from 'seleniumbase' (/usr/local/lib/python3.10/site-packages/seleniumbase/__init__.py)
[2025-08-19 07:19:59 -0400] [53] [INFO] Worker exiting (pid: 53)
[2025-08-19 07:19:59 -0400] [52] [ERROR] Worker (pid:53) exited with code 3
[2025-08-19 07:19:59 -0400] [52] [ERROR] Shutting down: Master
[2025-08-19 07:19:59 -0400] [52] [ERROR] Reason: Worker failed to boot.
```

## Steps To Reproduce
1. Start the docker and check log

## Expected Behavior
Start and work

## Debug Information
Cannot be done since no UI

## Environment Information
- BASE OS: Unraid

**Comment by Flashlab2** [comment]
I had the same: adding USE_CF_BYPASS=false fixed it for me for now.

**Comment by nodiaque** [comment]
But this remove the cloudflare bypass

**Comment by kennyboy55** [comment]
I just updated to the latest docker version and was experiencing the same issue, adding `USE_CF_BYPASS=false` did indeed fix the docker container crashing on startup. However, downloading any book now fails since the Cloudflare bypass is missing.

Log Attached.

[cwa-book-downloader-2025-08-19T13-07-49-redacted.log](https://github.com/user-attachments/files/21856235/cwa-book-downloader-2025-08-19T13-07-49-redacted.log)

**Comment by Flashlab2** [comment]
Yes, I haven't been able to use this for weeks now. All downloads fail.

**Comment by Flashlab2** [comment]
When you use DEBUG=true it also fails to load.

**Comment by geist325** [comment]
+1
USE_CF_BYPASS=false made it run again for me as well.
But yes still a problem.

**Comment by nodiaque** [comment]
Just a hint, just do a thumbsup instead of commenting the samething over and over. Also, since the log clearly show an error during the initiation of the cloudflare bypass, it's normal that removing the bypass make the docker work.

As for DEBUG=true, if you didn't put the bypass=false, it won't do anything since it's only for the gui.

**Comment by calibrain** [comment]
Hey ! I am aware of the issue and looking into it, should have a fix in the next hour or so, sorry about that

**Comment by calibrain** [comment]
Something weird happened upstream in some of the pip dependencies. 
I forced a version and this should work
I just merged #229, it takes ~30min to build, I will wait for it to finish building and test it again on my prod, and if it works will close this ticket

**Comment by calibrain** [comment]
Seems to be fixed now !

**Comment by Glennza1962** [comment]
Sorry but I just pulled the latest version and the problem is still there

ImportError: cannot import name 'Driver' from 'seleniumbase' (/usr/local/lib/python3.10/site-packages/seleniumbase/__init__.py)

[2025-08-20 06:25:49 +1000] [53] [INFO] Worker exiting (pid: 53)

[2025-08-20 06:25:49 +1000] [52] [ERROR] Worker (pid:53) exited with code 3

[2025-08-20 06:25:49 +1000] [52] [ERROR] Shutting down: Master

[2025-08-20 06:25:49 +1000] [52] [ERROR] Reason: Worker failed to boot.

**Comment by kennyboy55** [comment]
I also just pulled the latest version, and am still experiencing issues. I saw an email reply which seems to be missing here asking for the sha256.

```
$ docker inspect cwa-book-downloader --format='{{.Name}} - {{.Id}} - {{.Image}}'
/cwa-book-downloader - 1933b4eac49acfbe68f96bb53156a54340b14120517dba248ae2ff5ec3d1cb7c - sha256:56a899713d2a48485a0c71dd6e04c48e04df4a2beb7e8b87ec5bb4aee245b7bf
```

The docker compose
```
  cwa-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: cwa-book-downloader
    environment:
      FLASK_PORT: 8084
      LOG_LEVEL: info
      BOOK_LANGUAGE: "en,nl"
      USE_BOOK_TITLE: "true"
      USE_CF_BYPASS: "true"
      TZ: Europe/Amsterdam
      APP_ENV: prod
      UID: 1000
      GID: 1000
      CWA_DB_PATH: /auth/app.db
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - ./ingest:/cwa-book-ingest
      - ./cwa-config/app.db:/auth/app.db:ro
```

And attached the complete log file from container start to crash.

[cwa-book-downloader-2025-08-20T07-00-43-redacted.log](https://github.com/user-attachments/files/21885722/cwa-book-downloader-2025-08-20T07-00-43-redacted.log)
