### ISSUE TITLE
[BUG] Some DNS Issues

### ISSUE THREAD

**Issue by Glennza1962** [calibrain/calibre-web-automated-book-downloader#250]
I've been testing the DNS options and there are a few issues. Cloudflare works - with or without DOH but google doesn't want to work with DOH...

2025-08-27 11:39:21,503 - network - INFO - network.py:309 - Custom DNS resolver successfully configured and activated

2025-08-27 11:39:21,780 - network - INFO - network.py:260 - DoH server dns.google resolved to IP: 8.8.4.4

2025-08-27 11:39:21,781 - network - INFO - network.py:292 - DoH resolver successfully configured and activated

2025-08-27 11:39:21,781 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']

2025-08-27 11:39:22,364 - network - WARNING - network.py:143 - DoH resolution failed for annas-archive.org: 400 Client Error: Bad Request for url: https://dns.google/dns-query?name=annas-archive.org&type=AAAA

**Comment by Glennza1962** [comment]
Quad9 doesn't work at all. My suspicion is that there is an issue with the formatting of the IPv6 addresses. If I manually set the DNS server to 2620:fe::fe or 26620:fe::9, it ignores it. The IP4 ones are fine.

Some of the addresses are abbreviated and I don't think Downloader likes them. More info here...

https://www.geeksforgeeks.org/computer-networks/ipv6-addressing-format-and-conventions/




2025-08-27 11:43:11,300 - config - INFO - config.py:53 - CUSTOM_DNS: ['9.9.9.9', '149.112.112.112', '2620:fe::fe', '26620:fe::9']

2025-08-27 11:43:11,300 - config - INFO - config.py:59 - DOH_SERVER: https://dns.quad9.net/dns-query

2025-08-27 11:43:11,300 - config - INFO - config.py:67 - PROXIES: {}

2025-08-27 11:43:11,301 - config - INFO - config.py:77 - SUPPORTED_FORMATS: ['epub']

[2025-08-27 11:43:11 +1000] [53] [ERROR] Exception in worker process

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/dns/resolver.py", line 1198, in _enrich_nameservers

    raise NotImplementedError

NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker

    worker.init_process()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process

    self.load_wsgi()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi

    self.wsgi = self.app.wsgi()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi

    self.callable = self.load()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load

    return self.load_wsgiapp()

  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp

    return util.import_app(self.app_uri)

  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app

    mod = importlib.import_module(module)

  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/app/app.py", line 17, in <module>

    import backend

  File "/app/backend.py", line 16, in <module>

    import book_manager

  File "/app/book_manager.py", line 10, in <module>

    import downloader

  File "/app/downloader.py", line 3, in <module>

    import network

  File "/app/network.py", line 321, in <module>

    init_dns_resolvers()

  File "/app/network.py", line 316, in init_dns_resolvers

    init_custom_resolver()

  File "/app/network.py", line 297, in init_custom_resolver

    custom_resolver = create_custom_resolver()

  File "/app/network.py", line 149, in create_custom_resolver

    custom_resolver.nameservers = CUSTOM_DNS

  File "/usr/local/lib/python3.10/site-packages/dns/resolver.py", line 1231, in nameservers

    self._enrich_nameservers(nameservers, self.nameserver_ports, self.port)

  File "/usr/local/lib/python3.10/site-packages/dns/resolver.py", line 1200, in _enrich_nameservers

    raise ValueError(

ValueError: nameserver 26620:fe::9 is not a dns.nameserver.Nameserver instance or text form, IP address, nor a valid https URL

[2025-08-27 11:43:11 +1000] [53] [INFO] Worker exiting (pid: 53)

[2025-08-27 11:43:11 +1000] [52] [ERROR] Worker (pid:53) exited with code 3

[2025-08-27 11:43:11 +1000] [52] [ERROR] Shutting down: Master

[2025-08-27 11:43:11 +1000] [52] [ERROR] Reason: Worker failed to boot.

**Comment by calibrain** [comment]
Thank you ! And it seems there was a typo in the quad9 ipv6 address lol
#256 should fix that

**Comment by Glennza1962** [comment]
Still have this issue with google dns. It doesn't like DoH!

2025-08-31 08:02:31,574 - network - INFO - network.py:309 - Custom DNS resolver successfully configured and activated

2025-08-31 08:02:31,628 - network - INFO - network.py:260 - DoH server dns.google resolved to IP: 8.8.8.8

2025-08-31 08:02:31,629 - network - INFO - network.py:292 - DoH resolver successfully configured and activated

2025-08-31 08:02:31,629 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']

2025-08-31 08:02:31,989 - network - WARNING - network.py:143 - DoH resolution failed for annas-archive.org: 400 Client Error: Bad Request for url: https://dns.google/dns-query?name=annas-archive.org&type=AAAA

2025-08-31 08:02:32,990 - network - WARNING - network.py:143 - DoH resolution failed for annas-archive.org: 400 Client Error: Bad Request for url: https://dns.google/dns-query?name=annas-archive.org&type=A

**Comment by Glennza1962** [comment]
Same with quad9...


2025-08-31 08:09:05,349 - network - INFO - network.py:309 - Custom DNS resolver successfully configured and activated

2025-08-31 08:09:05,405 - network - INFO - network.py:260 - DoH server dns.quad9.net resolved to IP: 9.9.9.9

2025-08-31 08:09:05,406 - network - INFO - network.py:292 - DoH resolver successfully configured and activated

2025-08-31 08:09:05,407 - network - INFO - network.py:325 - AA_BASE_URL: auto, checking available urls ['https://annas-archive.org', 'https://annas-archive.se', 'https://annas-archive.li']

2025-08-31 08:09:05,675 - network - WARNING - network.py:143 - DoH resolution failed for annas-archive.org: 400 Client Error: Bad Request for url: https://dns.quad9.net/dns-query?name=annas-archive.org&type=AAAA

2025-08-31 08:09:05,743 - network - WARNING - network.py:143 - DoH resolution failed for annas-archive.org: 400 Client Error: Bad Request for url: https://dns.quad9.net/dns-query?name=annas-archive.org&type=A

**Comment by calibrain** [comment]
This one is tricky
I will probably rewrite most of the DOH implementation
But it will take some time

**Comment by calibrain** [comment]
@alexhb1  is working on a potential solution for this #336

**Comment by alexhb1** [comment]
Yep, I've fixed any remaining DOH related bugs and mostly rewritten the DOH function. `CUSTOM_DNS: auto` will also rotate between providers automatically if errors occur, so any small blips with connections will be fixed in the background.
