### ISSUE TITLE
Dupe'd files in CWA

### ISSUE THREAD

**Issue by nikkehsolaris** [calibrain/calibre-web-automated-book-downloader#98]
I'm seeing duplicate entries in CWA for each file downloaded; One you can't edit and throws a " Error editing book: list index out of range" error; the second entry correctly gets the metadata/etc. Files manually placed in the ingest folder do not have this issue.

I have a feeling CWA prematurely ingesting a non complete file; but I'm not 100% sure of that. Where does the downloader 'store' the file while the download is in progress?

**Comment by calibrain** [comment]
This shouldn't happen, we write to a temp folder then move it to the CWA folder once it finished processing properly
Could you share your compose ?

By default, we download to `/tmp/cwa-book-downloader` and then move to `/cwa-book-ingest`
(But you can override that by setting your own `TMP_DIR` and `INGEST_DIR` respectively)

**Comment by nikkehsolaris** [comment]
[CWADownloader.pdf](https://github.com/user-attachments/files/19299886/CWADownloader.pdf)

I'm running in Unraid so its via docker in a [Unraid template](https://raw.githubusercontent.com/nodiaque/unraid_template/master/nodiaque/calibre-web-automated-book-downloader-official.xml)

This is post me adding the tmp_dir value manually it is still dupe'ing. :(

Also I'm seeing alot of sub 60kb files downloaded when the book file in question is reported to be ~0.5mb or larger; any ideas on how to handle these 'broken' files?

**Comment by calibrain** [comment]
Could you share the logs / book ?
I will try to replicate the issue locally

Also, its extra weird since CWA does deduplication (well, Calibre does) if it detects the same SHA for the book

**Comment by nikkehsolaris** [comment]
![Image](https://github.com/user-attachments/assets/b100cee2-089f-47f8-8b6f-db9d2fd9d7f7)

![Image](https://github.com/user-attachments/assets/ffe85bd6-b5a7-4f99-b0ff-7e050d476c6c)

![Image](https://github.com/user-attachments/assets/d4241108-bfe8-4e2a-bf74-90642d1b523e)

[cwa-bookd-downloader.log](https://github.com/user-attachments/files/19354768/cwa-bookd-downloader.log)

**Comment by calibrain** [comment]
I just merged a "fix"
Not sure if this will work, but after doing some digging, it seems that even when using "mv" to move a file, if they are on different filesystem it will actually do a copy
So I use a temporary name while doing the "move" and then renaming it to its real name (atomically) once its done, hopefully this fixes it for you

**Comment by nikkehsolaris** [comment]
Still seeing dupe's BUT you did fix the phantom sub 60kb file issue! I'll do some more unraid testing and see if i can tweak any permissions settings to fix this. (Won't reopen this for now but will share if I figure it out.)

**Comment by calibrain** [comment]
Thank you for the update !
It's super weird, from your logs I only see one download, and one move, their might be some weird interactions with CWA or some new feature I am not aware of on their side too
If I think of any other solutions, I will be sure to update you too !
